# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNStyledDialogs' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RNStyledDialogs

  pod 'PMAlertController', :git => 'https://github.com/prscX/PMAlertController', :branch => 'swift-version-fix'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name.include?('PMAlertController')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.2'
        end
      end
    end
  end
end
